### ISSUE TITLE
AI Calls not Starting | Missing Event Trigger

### ISSUE THREAD

**Issue by Llama-Palooza** [Lanzaned-Enterprises/LENT-AICalls#1]
Don't ask me how I got on the other github page, haha.
![image](https://github.com/Lanzaned-Enterprises/LENT-AICalls/assets/124511433/36d66421-3c2f-46c5-b986-1036e41744e6)
This event isn't being triggered so no calls ever come through. Am I missing something?

**Comment by Llama-Palooza** [comment]
👎

**Comment by SerenaKing** [comment]
Apologies, Forgot to push the update...

The update below fixes the trigger on the hospital side.

https://github.com/Lanzaned-Enterprises/LENT-AICalls/commit/c56ac6d7ce10f68a242d6d6cab4c49efc2f7b0be

**Comment by Llama-Palooza** [comment]
> Apologies, Forgot to push the update...
> 
> The update below fixes the trigger on the hospital side.
> 
> [c56ac6d](https://github.com/Lanzaned-Enterprises/LENT-AICalls/commit/c56ac6d7ce10f68a242d6d6cab4c49efc2f7b0be)

Yes I know. My comment was supposed to be a thumbs up due to the fix, I apologize.

**Comment by Llama-Palooza** [comment]
My comment was supposed to be a thumbs up to remind you of it, my bad. Haha. Fat fingers.
